steps:
  - id: build-backend
    name: "docker"
    args:
      - build
      - --file=Dockerfile
      - "--tag=$_ARTIFACT_REPOSITORY_IMAGE_NAME:$SHORT_SHA"
      - "--tag=$_ARTIFACT_REPOSITORY_IMAGE_NAME:latest"
      - --cache-from=$_ARTIFACT_REPOSITORY_IMAGE_NAME:latest
      - .
  - id: push-backend
    name: "docker"
    args:
      - push
      - --all-tags
      - $_ARTIFACT_REPOSITORY_IMAGE_NAME
    waitFor: ["build-backend"]
  - id: deploy-backend
    name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - test-cloudbuild
      - --quiet
      - --platform=managed
      - --project=$PROJECT_ID
      - --region=$_REGION
      - --image=$_ARTIFACT_REPOSITORY_IMAGE_NAME:$SHORT_SHA
      - --no-use-http2
      - --update-secrets=MYSQL_USER=MYSQL_USER:latest
    waitFor: ["push-backend"]
  - id: traffic-to-latest
    name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - services
      - update-traffic
      - test-cloudbuild
      - --project=$PROJECT_ID
      - --region=$_REGION
      - --to-latest
    waitFor: ["deploy-backend"]

timeout: 3600s

substitutions:
  _TZ: UTC
  _APP_ENV: dev
  _REGION: asia-northeast1
  _ARTIFACT_REPOSITORY_IMAGE_NAME: asia-northeast1-docker.pkg.dev/iac-sandbox-0808/test-cloudbuild/hello-world-app

options:
  logging: CLOUD_LOGGING_ONLY
